remote_theme: "mmistakes/minimal-mistakes"
github: [metadata]
include: ["_pages"]
defaults:
  # _pages
  -
    scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

